server:
  host: 0.0.0.0
  port: 9000
  options:
    connections:
      routes:
        cors:
          origin:
            - 'http://0.0.0.0:4200'
            - 'http://localhost:4200'
            - 'http://127.0.0.1:4200'
logger:
  name: NwtSchoolFrontServer
swag:
  info:
    title: Server for NWT School Front in Angular