server:
  host: 0.0.0.0
  port: 4443
  options:
    connections:
      routes:
        cors: true


swag:
  info:
    title: New Web's Technologies course with Hapiness
mongodb:
  host: 0.0.0.0
  port: 27017
  db: cvdb